class Lenguajes:
    def __init__(self):
        pass
    
    def Español(self):
        español = {
            "Idioma_Selec": "Español",
            "Proyecto": "Proyecto",
            "Usuario": "Usuario",
            "Descripción": "Descripción",
            "Fecha": "Fecha",
            "Subir_Imagen": "Subir Imágen",
            "Titulo": "Título",
            "Creacion_Proyecto": "Creación de proyecto",
            "Documentos_Cargados": "Documentos cargados",
            "Agregar": "Agregar",
            "Aceptar": "Aceptar",
            "Cancelar": "Cancelar",
            "Crear_Proyecto": "Crear Proyecto",
            "Editar_Proyecto": "Editar Proyecto",
            
            "Opciones": "Opciones",
            "Autor": "Autor",
            "Visualizar": "Visualizar",
            "Ordenar_por": "Ordenar por",
            "Mejor_Calificado": "Mejor Calificado",
            "Peor_Calificado": "Peor Calificado",
            "Crear_Proyecto": "Crear Proyecto",
            "Editar_": "Editar",
            "Eliminar_": "Eliminar",
            "Fecha_creación": "Fecha de creación",
            "Archivos": "Archivos",
            "Escribe_comentario": "Escribe tu comentario.",
            "Comentar": "Comentar",
            "Cerrar": "Cerrar",
            "Puntuación": "Puntuación",
            "Bienvenido": "Bienvenido",
            "Página_principal": "Página principal",
            "Mis_proyectos": "Mis proyectos",
            "Proyectos": "Proyectos",
            "Cerrar_sesión": "Cerrar sesión",
            "Nuestro_sitio_web": "Nuestro sitio web",
            "Información": "Información"
        }
        return español

    def Ingles(self):
        ingles = {
            "Idioma_Selec": "English",
            "Proyecto": "Project",
            "Usuario": "User",
            "Descripción": "Description",
            "Fecha": "Date",
            "Subir_Imagen": "Upload Image",
            "Titulo": "Title",
            "Creacion_Proyecto": "Project creation",
            "Documentos_Cargados": "Loaded documents",
            "Agregar": "Add",
            "Aceptar": "Accept",
            "Cancelar": "Cancel",
            "Crear_Proyecto": "Create Project",
            "Editar_Proyecto": "Edit Project",
            
            "Opciones": "Options",
            "Autor": "Author",
            "Visualizar": "View",
            "Ordenar_por": "Order by",
            "Mejor_Calificado": "Best Rated",
            "Peor_Calificado": "Lowest Rated",
            "Crear_Proyecto": "Create Project",
            "Editar_": "Edit",
            "Eliminar_": "Delete",
            "Fecha_creación": "Creation Date",
            "Archivos": "Files",
            "Escribe_comentario": "Write your comment.",
            "Comentar": "Comment",
            "Cerrar": "Close",
            "Puntuación": "Score",
            "Bienvenido": "Welcome",
            "Página_principal": "Homepage",
            "Mis_proyectos": "My projects",
            "Proyectos": "Projects",
            "Cerrar_sesión": "Log out",
            "Nuestro_sitio_web": "Our website",
            "Información": "Information"
        }
        return ingles

    def Frances(self):
        frances = {
            "Idioma_Selec": "Français",
            "Proyecto": "Projet",
            "Usuario": "Utilisateur",
            "Descripción": "Description",
            "Fecha": "Date",
            "Subir_Imagen": "Télécharger l'image",
            "Titulo": "Titre",
            "Creacion_Proyecto": "Création de projet",
            "Documentos_Cargados": "Documents chargés",
            "Agregar": "Ajouter",
            "Aceptar": "Accepter",
            "Cancelar": "Annuler",
            "Crear_Proyecto": "Créer un projet",
            "Editar_Proyecto": "Modifier le projet",
            
            "Opciones": "Options",
            "Autor": "Auteur",
            "Visualizar": "Voir",
            "Ordenar_por": "Trier par",
            "Mejor_Calificado": "Le mieux noté",
            "Peor_Calificado": "Le moins bien noté",
            "Crear_Proyecto": "Créer un projet",
            "Editar_": "Modifier",
            "Eliminar_": "Éliminer",
            "Fecha_creación": "Date de création",
            "Archivos": "Fichiers",
            "Escribe_comentario": "Écrivez votre commentaire.",
            "Comentar": "Commenter",
            "Cerrar": "Fermer",
            "Puntuación": "Score",
            "Bienvenido": "Bienvenue",
            "Página_principal": "Page d'accueil",
            "Mis_proyectos": "Mes projets",
            "Proyectos": "Projets",
            "Cerrar_sesión": "Déconnexion",
            "Nuestro_sitio_web": "Notre site web",
            "Información": "Information"
        }
        return frances

    def Italiano(self):
        italiano = {
            "Idioma_Selec": "Italiano",
            "Proyecto": "Progetto",
            "Usuario": "Utente",
            "Descripción": "Descrizione",
            "Fecha": "Data",
            "Subir_Imagen": "Carica Immagine",
            "Titulo": "Titolo",
            "Creacion_Proyecto": "Creazione del progetto",
            "Documentos_Cargados": "Documenti caricati",
            "Agregar": "Aggiungere",
            "Aceptar": "Accettare",
            "Cancelar": "Annulla",
            "Crear_Proyecto": "Crea Progetto",
            "Editar_Proyecto": "Modifica Progetto",
            
            "Opciones": "Opzioni",
            "Autor": "Autore",
            "Visualizar": "Visualizza",
            "Ordenar_por": "Ordina per",
            "Mejor_Calificado": "Migliore valutazione",
            "Peor_Calificado": "Peggiore valutato",
            "Crear_Proyecto": "Crea progetto",
            "Editar_": "Modificare",
            "Eliminar_": "Eliminare",
            "Fecha_creación": "Data di creazione",
            "Archivos": "File",
            "Escribe_comentario": "Scrivi il tuo commento.",
            "Comentar": "Commenta",
            "Cerrar": "Chiudi",
            "Puntuación": "Punteggio",
            "Bienvenido": "Benvenuto",
            "Página_principal": "Pagina principale",
            "Mis_proyectos": "I miei progetti",
            "Proyectos": "Progetti",
            "Cerrar_sesión": "Esci",
            "Nuestro_sitio_web": "Il nostro sito web",
            "Información": "Informazione"
        }
        return italiano

    def Portugues(self):
        portugues = {
            "Idioma_Selec": "Português",
            "Proyecto": "Projeto",
            "Usuario": "Usuário",
            "Descripción": "Descrição",
            "Fecha": "Data",
            "Subir_Imagen": "Carregar Imagem",
            "Titulo": "Título",
            "Creacion_Proyecto": "Criação de projeto",
            "Documentos_Cargados": "Documentos carregados",
            "Agregar": "Adicionar",
            "Aceptar": "Aceitar",
            "Cancelar": "Cancelar",
            "Crear_Proyecto": "Criar Projeto",
            "Editar_Proyecto": "Editar Projeto",
            
            "Opciones": "Opções",
            "Autor": "Autor",
            "Visualizar": "Visualizar",
            "Ordenar_por": "Organizar por",
            "Mejor_Calificado": "Melhor avaliado",
            "Peor_Calificado": "Pior avaliação",
            "Crear_Proyecto": "Criar projeto",
            "Editar_": "Editar",
            "Eliminar_": "Eliminar",
            "Fecha_creación": "Data de criação",
            "Archivos": "Arquivos",
            "Escribe_comentario": "Escreva seu comentário.",
            "Comentar": "Comentar",
            "Cerrar": "Fechar",
            "Puntuación": "Pontuação",
            "Bienvenido": "Bem-vindo",
            "Página_principal": "Página principal",
            "Mis_proyectos": "Meus projetos",
            "Proyectos": "Projetos",
            "Cerrar_sesión": "Sair",
            "Nuestro_sitio_web": "Nosso site",
            "Información": "Informação"
        }
        return portugues